// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUpFeUPCyGXiyw-IQ3Jasj5Dy6dLEaEAI',
    appId: '1:65671916509:web:fe14b62ddf16e0a5686434',
    messagingSenderId: '65671916509',
    projectId: 'safety-app-e6b39',
    authDomain: 'safety-app-e6b39.firebaseapp.com',
    storageBucket: 'safety-app-e6b39.firebasestorage.app',
    measurementId: 'G-P8Y0371R9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1JY3KfNmxYbbweFyI_JBZ73uwk8ktpps',
    appId: '1:65671916509:android:0312c83fc6f303ce686434',
    messagingSenderId: '65671916509',
    projectId: 'safety-app-e6b39',
    storageBucket: 'safety-app-e6b39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADlTjIWB8VSGzPo8Q9vgkW2KYNB6LSuS0',
    appId: '1:65671916509:ios:be4d51358b81b504686434',
    messagingSenderId: '65671916509',
    projectId: 'safety-app-e6b39',
    storageBucket: 'safety-app-e6b39.firebasestorage.app',
    iosBundleId: 'com.example.awaaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADlTjIWB8VSGzPo8Q9vgkW2KYNB6LSuS0',
    appId: '1:65671916509:ios:be4d51358b81b504686434',
    messagingSenderId: '65671916509',
    projectId: 'safety-app-e6b39',
    storageBucket: 'safety-app-e6b39.firebasestorage.app',
    iosBundleId: 'com.example.awaaz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUpFeUPCyGXiyw-IQ3Jasj5Dy6dLEaEAI',
    appId: '1:65671916509:web:4c2d4a245d4d8692686434',
    messagingSenderId: '65671916509',
    projectId: 'safety-app-e6b39',
    authDomain: 'safety-app-e6b39.firebaseapp.com',
    storageBucket: 'safety-app-e6b39.firebasestorage.app',
    measurementId: 'G-CWCJTGQLY2',
  );
}
